//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service_Database.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceContract
    {
        public int Id { get; set; }
        public int MedicalServiceProvider { get; set; }
        public int InsuranceCompany { get; set; }
        public int Type { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany1 { get; set; }
        public virtual MedicalServiceProvider MedicalServiceProvider1 { get; set; }
        public virtual InsuranceContractType InsuranceContractType { get; set; }
    }
}
