//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service_Database.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class InsuranceContract
    {
        [XmlIgnore]
        public int Id { get; set; }
        public int MedicalServiceProviderId { get; set; }
        public int InsuranceCompanyId { get; set; }
        public int TypeId { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }

        [XmlIgnore]
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        [XmlIgnore]
        public virtual MedicalServiceProvider MedicalServiceProvider { get; set; }
        [XmlIgnore]
        public virtual InsuranceContractType InsuranceContractType { get; set; }
    }
}
