//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service_Database.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceServiceDatabaseEntities : DbContext
    {
        public InsuranceServiceDatabaseEntities()
            : base("name=InsuranceServiceDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public virtual DbSet<InsuranceContract> InsuranceContracts { get; set; }
        public virtual DbSet<InsuranceContractType> InsuranceContractTypes { get; set; }
        public virtual DbSet<MedicalServiceProvider> MedicalServiceProviders { get; set; }
        public virtual DbSet<MedicalServiceProviderType> MedicalServiceProviderTypes { get; set; }
    }
}
