//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service_Database.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceContractType
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
    }
}
